# Generated by Django 2.2.6 on 2020-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('product', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Single_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Singleproduct')),
                ('price', models.IntegerField()),
                ('offer', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
