# Generated by Django 2.2.6 on 2020-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Singleproduct')),
                ('price', models.IntegerField()),
                ('offer', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
