# Generated by Django 2.2.6 on 2020-04-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_electronic_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Single_product',
            new_name='Dress_product',
        ),
    ]
